services:
  # PHP Service
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: scanassiette-backend
    container_name: scanassiette-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./backend/docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - scanassiette-network
    depends_on:
      - db

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: scanassiette-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - scanassiette-network
    depends_on:
      - app

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: scanassiette-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-scanassiette}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-scanassiet}
    ports:
      - "3306:3306"
    volumes:
      - scanassiette-mysql-data:/var/lib/mysql
      - ./backend/docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - scanassiette-network

  # PHPMyAdmin Service (optionnel)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: scanassiette-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 100M
    ports:
      - "8080:80"
    networks:
      - scanassiette-network
    depends_on:
      - db

# Docker Networks
networks:
  scanassiette-network:
    driver: bridge

# Volumes
volumes:
  scanassiette-mysql-data:
    driver: local
